### ISSUE TITLE
how to acquire images when camera calibration hasn't been done yet?

### ISSUE THREAD

**Issue by rursprung** [FraunhoferIOSB/camera_aravis2#43]
the documentation doesn't seem to go into details about the camera-specific YAML file. however, it seems that it must contain the camera calibration data as otherwise the node doesn't start but fails with this error:
```
[camera_driver_uv-1] 1732350747.151898587: [camera_calibration_parsers] [WARN]  Exception parsing YAML camera calibration:
[camera_driver_uv-1] invalid node; first invalid key: "rows"
[camera_driver_uv-1] 1732350747.151932311: [camera_calibration_parsers] [ERROR] Failed to parse camera calibration from file [.../install/camera_aravis2/share/camera_aravis2/config/camera_info_cam1.yaml]
[camera_driver_uv-1] 1732350747.151983944: [camera_driver_cam1] [WARN]  Camera calibration file .../install/camera_aravis2/share/camera_aravis2/config/camera_info_cam1.yaml not found
```

this creates a bit of a chicken-and-egg problem: to do the camera calibration i need the images in a ROS topic so that i can use [image_pipeline's `camera_calibration`](https://docs.ros.org/en/rolling/p/camera_calibration/) functionality. but i can't seem to be able to start `camera_aravis2` without having the calibration data 😅

what is the recommended way to go about this?

on another note: the latter error message about the file not being found is wrong & misleading as the file does exist at the specified location, it just failed to parse it (since it didn't find the content it was looking for).

i had set the file to the following content (removing all calibration related options):
```
image_width: 2048
image_height: 1536
camera_name: cam1
```

**Comment by rursprung** [comment]
i now realised that i can simply put a null-matrix for the camera matrix & distortion coefficients and an identity matrix for the rectification & projection matrix:
```yaml
camera_matrix:
  rows: 3
  cols: 3
  data: [0, 0, 0,
         0, 0, 0,
         0, 0, 0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0, 0, 0, 0, 0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0,
         0, 1, 0,
         0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [1, 0, 0, 0,
         0, 1, 0, 0,
         0, 0, 1, 0]
```

is this the official way of doing it? if so, i think this should be documented somewhere.
though i think in the best case there's an easier way of achieving this to improve the out-of-the-box experience?
